---
title: "Named Entity Recognition"
author: Fitz Koch
date: today
description:  Uses the SQL tables setup in Data Engineering to run actual NER processing. 
format: 
  html:
    html-math-method: mathjax
    fig-responsive: true
    toc: true
    toc-location: left
    theme: cosmo
    page-layout: full
  ipynb:
    wrap: none
execute: 
  cache: true
editor:
    render-on-save: true
bibliography: /home/fitsl/library/zotero/fjk_library.bib
---


# Setup 

Navigate to root:
```{python}
import sys, os
from pathlib import Path

_project_root = Path.cwd()
while not (_project_root / "src").exists():
    _project_root = _project_root.parent
os.chdir(_project_root)
```

Set up imports and duckdb connection.
```{python}
import duckdb
import pandas as pd
from rapidfuzz import fuzz, process
from rapidfuzz.process import cdist
from rapidfuzz.fuzz import WRatio
from rapidfuzz.distance import DamerauLevenshtein as DL


# project imports
from src.NER_Matching import split_names, get_vocab, NER_pipeline

con = duckdb.connect()
``` 

## Loading joined data into duckdb

```{python}
large_files = Path("Data/large-files")
for file in large_files.glob("*.parquet"):
    con.execute(f"CREATE OR REPLACE VIEW {file.stem} AS SELECT * FROM read_parquet('{file}')")
```

```{python}
con.execute(f"""
    CREATE OR REPLACE VIEW long_reviews AS 
    SELECT * FROM read_parquet('Data/large-files/long_reviews/*.parquet')
""")
```

Grab the first df. 
```{python}
def get_movie(letterboxd_search):
    return con.execute("""
        SELECT * FROM long_reviews
        WHERE letterboxd_search = ?
    """, [letterboxd_search]).df()

movies = con.execute("""
    SELECT letterboxd_search FROM clean_metadata 
""").df()["letterboxd_search"]
df = get_movie(movies[0])
df
```

```{python}
def get_metadata(letterboxd_search):
    return con.execute("""
    SELECT * FROM clean_metadata 
    WHERE letterboxd_search = ?
    """, [letterboxd_search]).df()

metadata = get_metadata(movies[0])
metadata
```



# NER

## Planning 
1. Define fuzzy matching, and test it on some reviews to make sure we're satisfied. 
    1. Get all the individual words from all the reviews for a given df (a set)
    2. For every word in that set, match it against all the different NER groups built from the metadata to build a dictionary word -> [PLACEHOLDER]
        * actors
        * roles
        * directors
        * studios
        * genres
        * genre words (a dictionary we'll build by hand)
    3. Iterate over all the reviews for a df, and map each word by this. 
2. . Then run this fuzzy matching function on every row of the data frame. That's more sophisticated then I'm able to do in SQL, certainly, so we'll load it into pandas and do it there
3. Then if possible we want to figure out the budget. 
4. visualizations! (allotax, ranked list, etc.)



Then we need to get words to compare to. I don't like having nltk at root, so I just moved it around like this. 
```{python}
words_file = Path("nltk_data/corpora/words/en")
with open(words_file, "r") as f:
    english_words = set(f.read().splitlines())
```

First we need to get all the reviews for a given df and turn them into a giant set of words. 

```{python} 
from collections import defaultdict

vocab = get_vocab(df["review"])
actors = split_names(metadata["actors"].explode())

fuzzy_match_map = defaultdict(list)
for actor in list(actors):
    matches = process.extract(actor, vocab, scorer=fuzz.ratio, score_cutoff=70)
    for match, score, index in matches:
        fuzzy_match_map[actor].append((match, score))
print(fuzzy_match_map)
```

```{python}
fuzzy_match_map = defaultdict(list)
for actor in list(actors):
    threshold = max(0.85, 1.0 - 0.01 * len(actor))
    print(actor, threshold)
    matches = process.extract(
        actor, vocab, scorer=DL.normalized_similarity, score_cutoff=threshold
    )
    for match, score, index in matches:
        fuzzy_match_map[actor].append((match, score))
print(fuzzy_match_map)
```

This is a question of false positives; I think scaling by how long the word is makes sense. Anyway, we wrap this basic logic up as a loop over all the names from the metadata and we get the following:


```{python}
metadata.columns
n_df = df.copy()
n_df["ner_review"] = NER_pipeline(df, metadata)
n_df[["review", "ner_review"]].to_csv("scratch.csv")
n_df.to_csv("scratch.csv")
```


```{python}
num = 3
n_df, metadata = get_movie(movies[num]), get_metadata(movies[num])
n_df["ner_review"] = NER_pipeline(n_df, metadata)
n_df[["review", "ner_review"]].to_csv("scratch.csv")
n_df.head()
```



```{python}
mv_dir = Path("Data/large-files/ner_reviews")
mv_dir.mkdir(exist_ok=True, parents=True)
```

Rerun to remove the unnecessary chunk col:
```{python}
chunk_size = 500
buffer = []

for i, movie in enumerate(movies):
    n_df, metadata = get_movie(movie), get_metadata(movie)
    n_df["ner_review"] = NER_pipeline(n_df, metadata)
    buffer.append(n_df)

    if len(buffer) == chunk_size:
        chunk_id = i // chunk_size
        pd.concat(buffer).to_parquet(
            mv_dir / f"chunk_{chunk_id:04d}.parquet", index=False
        )
        buffer = []
        print(f"Saved chunk {chunk_id}")

# flush remainder
if buffer:
    pd.concat(buffer).to_parquet(
        mv_dir / f"chunk_{chunk_id + 1:04d}.parquet", index=False
    )
```

```{python}
con.execute("""
    CREATE OR REPLACE VIEW ner asc
    SELECT * FROM read_parquet('Data/large-files/ner_reviews/*.parquet')
""")

ner_df = con.execute("SELECT * FROM ner LIMIT 500").df()
ner_df.head()
```



# Visualization


```{python}

```